name: OctoBot-Prediction-Market-Docker
on:
  push:
    branches:
      - "master"
      - "dev"
    tags:
      - "*"
  pull_request:

permissions: read-all

jobs:
  docker:
    permissions:
      contents: read
      packages: write
    uses: Drakkar-Software/.github/.github/workflows/docker_workflow.yml@v1
    with:
      distribution_name: prediction-market
    secrets: inherit
